import { ai } from './ai';
import { createRoom, deleteRoom, joinRoom, leaveRoom, updateRoom } from './channel';
import { fetchLinkPreview, getChatMsg, uploadFile, handleFileSystem } from './chat';
import { checkHostToken, getConf, reloadConf, reloadLicense, updateAIConf, updateCreateSpaceConf } from './conf';
import { checkLicenseByIP, getLicenseByIP } from './license';
import { sendRecordRequest, updateRecord } from './record';
import {
  allSpaceInfos,
  checkUsername,
  createSpace,
  defineUserStatus,
  deleteSpaceParticipant,
  getSpaceInfo,
  getUniqueUsername,
  historySpaceInfos,
  joinSpace,
  leaveSpace,
  persistentSpace,
  updateOwnerId,
  updateSpaceAppAuth,
  updateSpaceApps,
  updateSpaceAppSync,
  updateSpaceParticipant,
  uploadSpaceApp,
  getUserMeta,
  updateSpaceInfo,
  deleteTodo,
  allowGuest,
  transOrSetOwnerManager,
  handleWorkMode,
  enterRoom,
  enterSpaceRoomFromLink,
  updateAuthRBACConf,
  deleteSpace,
} from './space';

export const api = {
  // ---- space api --------
  updateAuthRBACConf,
  enterSpaceRoomFromLink,
  enterRoom,
  joinSpace,
  updateSpaceInfo,
  createSpace,
  allSpaceInfos,
  historySpaceInfos,
  getUniqueUsername,
  checkUsername,
  defineUserStatus,
  getSpaceInfo,
  updateOwnerId,
  deleteSpaceParticipant,
  updateSpaceParticipant,
  updateSpaceApps,
  leaveSpace,
  persistentSpace,
  allowGuest,
  uploadSpaceApp,
  updateSpaceAppSync,
  updateSpaceAppAuth,
  deleteTodo,
  transOrSetOwnerManager,
  checkHostToken,
  handleWorkMode,
  deleteSpace,
  // ---- chat api --------
  fetchLinkPreview,
  getChatMsg,
  uploadFile,
  handleFileSystem,
  // ---- license api --------
  getLicenseByIP,
  checkLicenseByIP,
  // ---- recording api --------
  sendRecordRequest,
  updateRecord,
  // ---- channel api --------
  createRoom,
  deleteRoom,
  leaveRoom,
  joinRoom,
  updateRoom,
  getConf,
  updateAIConf,
  reloadConf,
  updateCreateSpaceConf,
  reloadLicense,
  // ---- platform api --------
  getUserMeta,
  ai,
};
