# docker-compose -f docker-compose.amd.yml up --build -d
services:
  vocespace:
    container_name: vocespace
    image: privoce/vocespace:latest
    build:
      context: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY:-devkey}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET:-secret}
      - LIVEKIT_URL=${LIVEKIT_URL:-ws://localhost:7880}
      - NEXT_PUBLIC_BASE_PATH=${NEXT_PUBLIC_BASE_PATH:-}
      - PORT=${PORT:-3000}
      - TURN_CREDENTIAL=${TURN_CREDENTIAL:-}
      - TURN_URL=${TURN_URL:-}
      - TURN_USERNAME=${TURN_USERNAME:-}
      - NEXT_PUBLIC_RESOLUTION=${NEXT_PUBLIC_RESOLUTION:-1080p}
    volumes:
      - npm-cache:/app/.npm-cache
      - uploads:/app/uploads
    depends_on:
      - livekit
    networks:
      - vocespace-network

volumes:
  npm-cache:
  uploads:

networks:
  vocespace-network:
    driver: bridge