version: '3.8'

services:
  # 生产环境 (vocespace.com/chat)
  livemeet-prod:
    build:
      context: .
      # args:
      #   - LIVEKIT_API_KEY=${LIVEKIT_API_KEY:-devkey}
      #   - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET:-secret}
      #   - LIVEKIT_URL=${LIVEKIT_URL:-wss://space.voce.chat}
      #   - NEXT_PUBLIC_BASE_PATH=/chat
      #   - TURN_CREDENTIAL=${TURN_CREDENTIAL:-}
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY:-devkey}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET:-secret}
      - LIVEKIT_URL=${LIVEKIT_URL:-wss://space.voce.chat}
      - NEXT_PUBLIC_BASE_PATH=/chat
      - TURN_CREDENTIAL=${TURN_CREDENTIAL:-}
    networks:
      - livemeet

  # Nginx反向代理
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deploy/nginx/sites:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/vocespace/vocespace_com:/var/vocespace/vocespace_com:ro  # 静态文件挂载
    depends_on:
      - livemeet-prod
    networks:
      - livemeet

networks:
  livemeet:
    driver: bridge