import { act, cleanup, renderHook } from '@testing-library/react';
import { afterEach, expect, it, vi } from 'vitest';
const state=vi.hoisted(()=>({device:'phone',emit:vi.fn(),chat:{msgs:[],unhandled:0},t:(key:string)=>key}));
vi.mock('@/lib/api',()=>({api:{}}));
vi.mock('@/lib/i18n/i18n',()=>({useI18n:()=>({t:state.t})}));
vi.mock('@/lib/hooks/use-layout-device',()=>({useLayoutDevice:()=>state.device}));
vi.mock('@/lib/hooks/use-visual-viewport',()=>({useVisualViewport:()=>null}));
vi.mock('@/lib/realtime/socket',()=>({socket:{emit:state.emit}}));
vi.mock('@/lib/store',()=>({useRoomStore:Object.assign((selector:any)=>selector({chatMsg:state.chat}),{getState:()=>({setChatMsg:vi.fn()})})}));
vi.mock('@livekit/components-react',()=>({useLocalParticipant:()=>({localParticipant:{identity:'self',name:'Me'}})}));
import { useChat } from '@/features/chat/hooks/useChat';
afterEach(()=>{cleanup();vi.clearAllMocks();state.device='phone';});
it('retains a draft on resize and does not send while an IME is composing',()=>{
  const space={name:'space',localParticipant:{identity:'self',name:'Me'}};
  const {result,rerender}=renderHook(()=>useChat({space,spaceInfo:{},messageApi:{},sendFileConfirm:vi.fn()} as any,null));
  act(()=>result.current.setValue('你好'));
  state.device='pc';rerender();
  expect(result.current.value).toBe('你好');
  const key:any={key:'Enter',shiftKey:false,keyCode:13,nativeEvent:{isComposing:true},preventDefault:vi.fn()};
  act(()=>result.current.handleKeyDown(key));expect(state.emit).not.toHaveBeenCalled();
  act(()=>result.current.handleKeyDown({...key,keyCode:229,nativeEvent:{isComposing:false}}));
  expect(state.emit).not.toHaveBeenCalled();
  act(()=>result.current.handleKeyDown({...key,nativeEvent:{isComposing:false}}));
  expect(state.emit).toHaveBeenCalledWith('chat_msg',expect.objectContaining({message:'你好',roomName:'space'}));
  expect(result.current.value).toBe('');
});
