import { ai } from '@/features/ai/api';
import { createRoom, deleteRoom, joinRoom, leaveRoom, updateRoom } from '@/features/channels/api';
import {
  fetchLinkPreview,
  getChatMsg,
  uploadFile,
  handleFileSystem,
  handleTilePlayerFile,
} from '@/features/chat/api';
import { sendFeedback, uploadFeedbackFile } from '@/features/feedback/api';
import {
  checkHostToken,
  getConf,
  reloadConf,
  reloadLicense,
  reloadRoomLicense,
  setupConf,
  updateAIConf,
  updateHyperbeamConf,
  updateCreateSpaceConf,
  updateSMTPConf,
} from '@/features/settings/api';
import {
  cancelLicenseSubscription,
  checkLicenseByIP,
  getLicenseByIP,
  getAllLicenses,
  createLicense,
  updateLicense,
  deleteAllLicenses,
  validateLicenseValue,
} from '@/features/license/api';
import { sendRecordRequest, updateRecord } from '@/features/recording/api';
import {
  testS3Connection,
  getS3Records,
  generateS3DownloadUrl,
  deleteS3Object,
} from '@/features/recording/storage-api';
import {
  allSpaceInfos,
  checkUsername,
  createSpace,
  defineUserStatus,
  deleteSpaceParticipant,
  getSpaceInfo,
  getUniqueUsername,
  historySpaceInfos,
  joinSpace,
  leaveSpace,
  persistentSpace,
  updateOwnerId,
  updateSpaceAppAuth,
  updateSpaceApps,
  updateSpaceAppSync,
  updateSpaceParticipant,
  uploadSpaceApp,
  getUserMeta,
  updateSpaceInfo,
  deleteTodo,
  allowGuest,
  transOrSetOwnerManager,
  handleWorkMode,
  enterRoom,
  enterSpaceRoomFromLink,
  updateAuthRBACConf,
  deleteSpace,
  flushdb,
} from '@/features/spaces/api';

export const api = {
  // ---- space api --------
  updateAuthRBACConf,
  enterSpaceRoomFromLink,
  enterRoom,
  joinSpace,
  updateSpaceInfo,
  createSpace,
  allSpaceInfos,
  historySpaceInfos,
  getUniqueUsername,
  checkUsername,
  defineUserStatus,
  getSpaceInfo,
  updateOwnerId,
  deleteSpaceParticipant,
  updateSpaceParticipant,
  updateSpaceApps,
  leaveSpace,
  persistentSpace,
  allowGuest,
  uploadSpaceApp,
  updateSpaceAppSync,
  updateSpaceAppAuth,
  deleteTodo,
  transOrSetOwnerManager,
  checkHostToken,
  handleWorkMode,
  deleteSpace,
  flushdb,
  // ---- chat api --------
  fetchLinkPreview,
  getChatMsg,
  uploadFile,
  handleFileSystem,
  handleTilePlayerFile,
  uploadFeedbackFile,
  sendFeedback,
  // ---- license api --------
  getLicenseByIP,
  cancelLicenseSubscription,
  checkLicenseByIP,
  getAllLicenses,
  createLicense,
  updateLicense,
  deleteAllLicenses,
  validateLicenseValue,
  // ---- recording api --------
  sendRecordRequest,
  updateRecord,
  // ---- s3 api --------
  testS3Connection,
  getS3Records,
  generateS3DownloadUrl,
  deleteS3Object,
  // ---- channel api --------
  createRoom,
  deleteRoom,
  leaveRoom,
  joinRoom,
  updateRoom,
  getConf,
  updateAIConf,
  updateSMTPConf,
  updateHyperbeamConf,
  setupConf,
  reloadConf,
  updateCreateSpaceConf,
  reloadLicense,
  reloadRoomLicense,
  // ---- platform api --------
  getUserMeta,
  ai,
};
